services:
  java_app:
    container_name: subscribe_app
    image: pekoniko/java_app:1.0.0
    build: .
    ports:
      - 8081:8080
    environment:
      DATABASE_URL: jdbc:postgresql://java_db:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - java_db
  java_db:
    container_name: subscribe_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}